//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenzerheide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BewertungHotel
    {
        public int Id { get; set; }
        public int BewertungId { get; set; }
        public int HotelId { get; set; }
        public int Sterne { get; set; }
        public string Kommentar { get; set; }
    
        public virtual Bewertung Bewertung { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
