//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenzerheide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmer_Zusatzleistung
    {
        public int Id { get; set; }
        public int ZimmerId { get; set; }
        public int ZusatzleistungId { get; set; }
    
        public virtual Zimmer Zimmer { get; set; }
        public virtual Zusatzleistung Zusatzleistung { get; set; }
    }
}
