//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenzerheide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zimmer()
        {
            this.BewertungZimmer = new HashSet<BewertungZimmer>();
            this.Reservation = new HashSet<Reservation>();
            this.Zimmer_Zusatzleistung = new HashSet<Zimmer_Zusatzleistung>();
        }
    
        public int Id { get; set; }
        public int HotelId { get; set; }
        public int RaumNummer { get; set; }
        public int AnzahlRaeume { get; set; }
        public int Kategorie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BewertungZimmer> BewertungZimmer { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zimmer_Zusatzleistung> Zimmer_Zusatzleistung { get; set; }
    }
}
